name: Génération Doc Doxygen et UML

on:
  push:
    branches:
      - '**'

permissions:
  contents: write

# Correction de la dépréciation Node.js
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer les outils (Doxygen, Graphviz, PlantUML)
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz plantuml python3-pip
          pip install hpp2plantuml

      - name: Générer le diagramme UML automatique
        run: |
          # Recherche récursive de tous les headers .h du projet
          find . -name "*.h" -not -path "./tests/*" -not -path "./build/*" > headers_list.txt
          hpp2plantuml -i headers_list.txt -o architecture_auto.puml || true
          
          if [ -f architecture_auto.puml ]; then
            plantuml -tsvg architecture_auto.puml
          else
            echo "Avertissement : Aucun diagramme généré."
          fi

      - name: Générer la documentation Doxygen
        run: doxygen Doxyfile

      - name: Préparer les fichiers pour le déploiement
        run: |
          mkdir -p ./doc_output/html/images
          [ -f architecture_auto.svg ] && cp architecture_auto.svg ./doc_output/html/images/ || echo "Pas de SVG à copier"

      - name: Déployer sur GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4 # Passage à la v4 pour support Node récent
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc_output/html
